### ISSUE TITLE
error on running 

### ISSUE THREAD

**Issue by mcsJDF01** [lapolis/LazyOSINT#6]
Hi, me again! Still love this. Not sure what has happened, but I can't seem to get it to run at all now, either on a new system or an existing installation. I get the following error:
Traceback (most recent call last):
  File "./main.py", line 169, in <module>
    main()
  File "./main.py", line 162, in main
    lin = [ x.result() for x in concurrent.futures.as_completed( linkedinT ) ]
  File "./main.py", line 162, in <listcomp>
    lin = [ x.result() for x in concurrent.futures.as_completed( linkedinT ) ]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/LazyOSINT/lib/linkedinCompanyScraper.py", line 185, in scrapeThoseEmployeez
    self.login( email , password )
  File "/home/user/LazyOSINT/lib/linkedinCompanyScraper.py", line 81, in login
    element = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.ID, "profile-nav-item")))
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

I've tried updating everything, removing all the requirements using pip and then reinstalling. I am sure its a requirement version wrong, but can't seem to identify which one.

**Comment by lapolis** [comment]
I might have an idea. Can you just let me know:
- Full command used ( you can exclude you LinkedIn email and passwd :D ) 
- OS and OS' version in use

It looks like it cannot find an element on the LinkedIn page so either that company has a weird LinkedIn page or the URL you input is not the home of the company's profile or, for some reason LinkedIn changed some tags.

**EDIT**: got the same error, quiet sure LinkedIn changed some tags. I will get back to you as soon as I find out more.

**Comment by lapolis** [comment]
Hey there!

It should be fixed now, please re-download it and let me know if it works!

**Comment by mcsJDF01** [comment]
Yep that works! First class service again, thank you!

**Comment by lapolis** [comment]
> Yep that works! First class service again, thank you!

Thank to you for making me notice the bug! 

Speak to you at the next one :D
